🎉 RFC：にゃーんへのイベント管理権限の付与
approvers/RFCs pull request #8
Opened 2021-10-14 16:04 UTC by merunno

### にゃーんへのイベント管理権限の付与

限界開発鯖内のロール **"にゃーん"**(鯖内権限) に イベント管理権限(`Management_Events`) を付与することを提案します。

2021-10-14 16:13 UTC, MikuroXina reviewed
PR のコメントの番号を合わせたり, Markdown 中の画像は複製してアップロードしておいたほうがよいと思います.

2021-10-14 16:23 UTC, soshiharami commented on docs/0004-にゃーんのイベント管理権限.md
> +| にゃーん   | イベントの管理 | 限界開発鯖全メンバーのうち `限界治安部隊` を持ったユーザー及び所有者権限をもったいっそうさんを除いた 81 人 |
全知全能の神除かれる一覧も含まれるのでは....?

2021-10-14 16:23 UTC, soshiharami commented on docs/0004-にゃーんのイベント管理権限.md
> +| ステージチャンネル | 大規模コミュニティーで利用できるステージチャンネルを使ったイベントの運営に最適 限界開発鯖では使えない |
今後使えるようになる可能性はあるので記述の仕方を変えたほうがいいかも...?

2021-10-14 16:23 UTC, soshiharami commented on docs/0004-にゃーんのイベント管理権限.md
> +今の所、ありませんが、ベータ版のため次期に使えなくなる可能性があります。
クッソどうでもいいけど、「今の所ありませんが、ベータ....」のほうが良くない？

2021-10-14 16:26 UTC, merunno commented on docs/0004-にゃーんのイベント管理権限.md
> +| ステージチャンネル | 大規模コミュニティーで利用できるステージチャンネルを使ったイベントの運営に最適 限界開発鯖では使えない |
![image](https://user-images.githubusercontent.com/82575685/137358358-66df9e2e-2374-41a7-837f-36bc5df0f79d.png)

2021-10-14 16:29 UTC, shun-shobon requested changes

2021-10-14 16:29 UTC, shun-shobon commented on docs/0004-にゃーんのイベント管理権限.md
> +![image](./images/RFCs-0004/image-1.png)
altを適切に設定してください。

2021-10-14 16:29 UTC, shun-shobon commented on docs/0004-にゃーんのイベント管理権限.md
> +![image*2](./images/RFCs-0004/image-2.png)
ここも同様。

2021-10-14 16:37 UTC, soshiharami submitted a review, later dismissed

2021-10-14 16:40 UTC, shun-shobon requested changes

2021-10-14 16:40 UTC, shun-shobon commented on docs/0004-にゃーんのイベント管理権限.md
> +今の所ありませんが、ベータ版のため正式版が出てくるまで使えなくなったりする可能性があります。
全く無いものではないと思いますので想定の範囲内でこの権限を悪用したときの影響を書いていただけると議論の種になるかと思います。

2021-10-14 16:40 UTC, shun-shobon commented on docs/0004-にゃーんのイベント管理権限.md
> +| にゃーん   | イベントの管理 | 限界開発鯖全メンバーのうち `限界治安部隊・全知全能の神` を持ったユーザー及び所有者権限をもったいっそうさんを除いた 80 人 |
この方がわかりやすいかと。

```suggestion
| にゃーん   | イベントの管理 | 限界開発鯖全メンバーのうち `限界治安部隊` 及び `全知全能の神` を持ったユーザー及び所有者権限をもったいっそうさんを除いた 80 人 |
```

2021-10-14 16:42 UTC, YukiYuigishi approved these changes, later dismissed

2021-10-14 16:47 UTC, YukiYuigishi submitted a review, later dismissed

2021-10-14 21:31 UTC, isso0424 requested changes
お気持ち表明です

2021-10-14 21:31 UTC, isso0424 commented on docs/0004-にゃーんのイベント管理権限.md
> +| にゃーん   | イベントの管理 | 限界開発鯖全メンバーのうち `限界治安部隊` 及び `全知全能の神` を持ったユーザー及び所有者権限をもったいっそうさんを除いた 80 人 |
これメンバー数には流動性があるので明記しないほうがいいと思うんだけどどうだろう

2021-10-14 21:31 UTC, isso0424 commented on docs/0004-にゃーんのイベント管理権限.md
> +| 他の場所           | 例えば いっそうさん「めるさん、茨城来ない？」など、特定の場所で行うイベントの運営に最適 |
これ形式っていう列の名前なら「ステージチャンネルを用いたイベント」とか言う感じの方が自然な気がする
「イベント運営に最適」っていう文言居るのかな

あと「他の場所」の例として急に話し言葉入ってくるのも気になる
普通に「上記二点に当てはまらないイベント」でよくね

2021-10-14 22:59 UTC, Colk-tech commented on docs/0004-にゃーんのイベント管理権限.md
> +| にゃーん   | イベントの管理 | 限界開発鯖全メンバーのうち `限界治安部隊` 及び `全知全能の神` を持ったユーザー及び所有者権限をもったいっそうさんを除いた 80 人 |
これは確かにそうだと思っていて、でもその反面影響の大きさを示すためには必要なので、「約n人 (yyyy年mm月dd日)」みたいに書き換えるのがいいと思います

2021-10-14 23:00 UTC, Colk-tech commented on docs/0004-にゃーんのイベント管理権限.md
> +| 他の場所           | 例えば いっそうさん「めるさん、茨城来ない？」など、特定の場所で行うイベントの運営に最適 |
限界LTやオフ会という具体的な使用ニーズな想定されているので、「イベント運営に最適」と「他の場所」という文言で問題ないと思っています

2021-10-14 23:05 UTC, Colk-tech submitted a review, later dismissed
この前の「おちんちんパーティ」みたいな頭悪い文化が生えそうなので賛成です。

2021-10-15 03:01 UTC, laminne approved these changes, later dismissed

2021-10-15 07:33 UTC, siketyan requested changes

2021-10-15 07:33 UTC, siketyan commented on docs/0004-にゃーんのイベント管理権限.md
> +この RFCs では限界開発鯖内のロール **"にゃーん"**(鯖内権限) に イベント管理権限(`Management_Events`) を付与することを提案します。
```suggestion
この RFC では限界開発鯖内のロール **"にゃーん"**(鯖内権限) に イベント管理権限(`Management_Events`) を付与することを提案します。
```

2021-10-15 07:33 UTC, siketyan commented on docs/0004-にゃーんのイベント管理権限.md
> +この RFCs により以下の権限が変更されます。
```suggestion
この RFC により以下の権限が変更されます。
```

2021-10-15 08:52 UTC, MikuroXina requested changes

2021-10-15 08:52 UTC, MikuroXina commented on docs/0004-にゃーんのイベント管理権限.md
> +この表を見ていただくとわかると思いますが、 "限界オフ" や "限界突発 LT" などイベントを行う我々にとってはとても役に立つ物だと思います。
「"限界突発 LT" にはボイスチャンネル形式のイベントを, "限界オフ" には他の場所の形式のイベントを利用することで, サーバーでの活動に役立つ」というように, 実際の利用に対応付けた文言を追加するのはどうでしょうか.

2021-10-15 08:52 UTC, MikuroXina commented on docs/0004-にゃーんのイベント管理権限.md
> +そのため、リスクも少ないことから **限界開発鯖におけるメンバーシップ権限ロール "にゃーん" にイベント管理権限を付与することを提案します。**
イベントを削除できるリスクを運用において小さいリスクとするのは不自然かもしれません. にゃーんに ウェブフックの管理 の権限を付与していないのは「ウェブフックの削除などによる不必要な破壊的変更を防ぐ。」ためなのです. ひょっとしたら削除合戦のような文化ができるやもしれませんが.

2021-10-15 17:20 UTC, shun-shobon submitted a review, later dismissed
僕の指摘箇所は直ってるようなのでApproveします。お疲れさまでした。

2021-10-16 00:39 UTC, MikuroXina submitted a review, later dismissed

2021-10-16 19:08 UTC, isso0424 approved these changes, later dismissed
お気持ち表明です

2021-10-16 19:08 UTC, soshiharami submitted a review, later dismissed

2021-10-16 19:09 UTC, merunno commented
@siketyan  approveお願いできますか.... (ごめんなさい)

2021-10-17 00:58 UTC, siketyan requested changes

2021-10-17 00:58 UTC, siketyan commented on docs/0004-にゃーんのイベント管理権限.md
> +![イベント開始前の形式選択画面](./images/RFCs-0004/image-1.png)
このあたりも RFCs のままになっております

```suggestion
![イベント開始前の形式選択画面](./images/RFC-0004/image-1.png)
```

2021-10-17 03:55 UTC, MikuroXina approved these changes

2021-10-17 03:56 UTC, soshiharami approved these changes

2021-10-17 03:57 UTC, siketyan approved these changes

2021-10-17 04:03 UTC, merged